### PR TITLE
Reorganize NewSongForm to use version of fractal structure.

### PR DESCRIPTION
**Pull request by jhb188**
I pulled the `NewSongForm` out of the `SongList` to give an example of what I think is a simpler fractal file pattern, as well as to prepare for the redux refactor of that component.

```
components/
  NewSong/
    index.js -- exports NewSong, (optionally) describes how to get data to NewSong.js as props
    NewSong.js -- describes how to get from `props` to a DOM representation, renders NewSongForm as a child
    NewSong.test.js -- tests NewSong.js
    NewSongForm/
      index.js
      NewSongForm.js
      NewSongForm.test.js (not implemented)
```

So, this file structure mimics the structure of the DOM representation we are producing, with all components dirs having the same
```
ComponentName/
  index.js -- possibly enhanced
  ComponentName.js -- primitive
  ComponentName.test.js -- test of primitive
  ComponentChild/
    ...
```
pattern.

Feel free to disagree, but I think the camelCase dir introduced in the other fractal structure proposal makes the tree less intuitive/predictable.

### CODE REVIEW

**Comment by rossvz** [comment]
I think that makes sense. Is there any difference for page-based components? Obviously right now we just have a single page and no routing or anything involved, I noticed in that other fractal article they use a "page" directory to organize those higher level nodes on the tree.

**Comment by rossvz** [comment]
Also, do we use the Component -> index.js for every component or just containers that need to connect to redux store?

**Comment by jhb188** [comment]
I don't use a separate dir for top-level "page" components. In an app with a router, I would probably expect every direct child of `src/components/` to be a page. I usually throw multi-use/leaf components in `src/components/shared/` or publish them in a separate npm lib.

Also, I think every component dir should have an `index.js`, even if that module just imports `MyComponent.js` and reexports it. That way, we already have a place to add enhancers if/when we need to without rearranging/renaming files, and the direct parent of `MyComponent` is always going to import from `./MyComponent`, rather than `./MyComponent/MyComponent.js` or something else.

**Comment by jhb188** [comment]
@rossvz cool if I merge this? I want to get the test config into the other branch so I can write some unit tests for the song filtering logic.

**Pull request merged**
